const cartTypes = {
  ADD_TO_CART_START: "ADD_TO_CART_START",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  REMOVE_CART_ITEM_START:"REMOVE_CART_ITEM",
  REMOVE_CART_ITEM_END:"REMOVE_CART_ITEM_END",
  DECREMENT_PRODUCT_QUANTITY_START:"DECREMENT_PRODUCT_QUANTITY",
  DECREMENT_PRODUCT_QUANTITY_END:"DECREMENT_PRODUCT_QUANTITY_END"
};

export default cartTypes;
