const productTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_END: "FETCH_PRODUCTS_END",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCTS_WITH_FILTER_START: "FETCH_PRODUCTS_WITH_FILTER_START",
  FETCH_PRODUCTS_WITH_FILTER_SUCCESS: "FETCH_PRODUCTS_WITH_FILTER_SUCCESS",
  FETCH_PRODUCTS_WITH_FILTER_FAIL: "FETCH_PRODUCTS_WITH_FILTER_FAIL",
  SET_PRODUCT: "SET_PRODUCT",
  FETCH_PRODUCTS_DETAILS_START: "FETCH_PRODUCTS_DETAILS_START",
  FETCH_PRODUCTS_DETAILS_SUCCESS: "FETCH_PRODUCTS_DETAILS_SUCCESS",
  FETCH_PRODUCTS_DETAILS_FAIL: "FETCH_PRODUCTS_DETAILS_FAIL",
  SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",
};

export default productTypes;
