const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAIL: "SIGN_IN_FAIL",
  SIGN_IN_USER_START: "SIGN_IN_USER_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SET_CURRENT_USER_ACTIVE: "SET_CURRENT_USER_ACTIVE",
  SET_CURRENT_USER_INACTIVE: "SET_CURRENT_USER_INACTIVE",
  LOGOUT_USER_START: "LOGOUT_USER_START",
  LOGOUT_USER_END: "LOGOUT_USER_END",
  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
};

export default userTypes;
